// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcsbemjusqrjrbnhzfxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpjc2JlbWp1c3FyanJibmh6ZnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Mzg0NTYsImV4cCI6MjA3MzMxNDQ1Nn0.i8OdJn9VhwU1kDu5WAUaJ1ZDh0RRzSIW2xmmLltz5qg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});